default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: epromo_test_development

test:
  <<: *default
  database: epromo_test_test

production:
  <<: *default
  host: ec2-54-243-203-87.compute-1.amazonaws.com
  database: d2hdjo2qkrqmog
  username: jkrhnzwniewzvp
  password: BdEnZ5i4fchT6l3E05L7GJWkWR
